name: Code style check

on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: npm install prettier --force
      - name: Prettify code
        run: npx prettier --check .
