name: Typescript compile check

on:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: npm install --force
      - name: compile extension
        run: |
          cd src
          npm run build
          cd ..
